export { admisiones } from "./admisiones";
export { asistencias } from "./asistencias";
export { calendario } from "./calendario";
export { comunicacion } from "./comunicacion";
export { finanzas } from "./finanzas";
export { gestionAcademica } from "./gestionacademica";
export { identidad } from "./identidad";
export { notificaciones } from "./notificaciones";
export { vidaEscolar } from "./vidaescolar";
