spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/base-app}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:P4ssword!}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

  docker:
    compose:
      enabled: false

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/school-system}
      database: ${SPRING_DATA_MONGODB_DATABASE:comunicacion}
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 60000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100ms

  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${SPRING_MAIL_SMTP_STARTTLS_ENABLE:false}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR

springdoc:
  pathsToMatch: /, /api/**

jwt:
  secret: secretClaveMuySegura123456789012345678901234567890
  expiration: 86400000

app:
  notifications:
    mail:
      enabled: ${APP_NOTIFICATIONS_MAIL_ENABLED:true}
      from: ${APP_NOTIFICATIONS_MAIL_FROM:notificaciones@ecep.edu.ar}
  portal:
    admissions-base-url: ${APP_PORTAL_ADMISSIONS_BASE_URL:http://localhost:3000/entrevista}

logging:
  level:
    root: INFO
    io.lettuce.core: ${APP_LOG_LEVEL_LETTUCE:WARN}
    org.springframework.data.redis: ${APP_LOG_LEVEL_SPRING_REDIS:WARN}
